version: "2"

services:
  web:
    build: .
    command: sh docker-entrypoint.sh
      DJANGO_SECRET_KEY: 'mg=p=lh)%lc-yajgu366%4p^*x_ip7)j*%l3*mr6#uptf&^ove'
    volumes:
      - ./:/srv/music

  nginx:
    extends:
      file: common.yml
      service: nginx
    depends_on:
      - web
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - web:ro
    ports:
      - 80:80
