version: "2"

services:
  web:
    build: .
    command: sh docker-entrypoint.sh
    volumes:
      - ./:/srv/music

  nginx:
    image: nginx:1.10-alpine
    depends_on:
      - web
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - web:ro
    ports:
      - 80:80